services:
  aigitcommit:
    build:
      context: .
    network_mode: host
    environment:
      OPENAI_API_BASE: ""
      OPENAI_API_TOKEN: ""
      OPENAI_MODEL_NAME: ""
      OPENAI_API_PROXY: ""

    volumes:
      - .:/repo:ro
